### PR TITLE
View profiles on main

### PR DESCRIPTION
**Pull request by faraznaeem**
### PT

https://www.pivotaltracker.com/story/show/161279744

### Tasks
Added styling to index page
added Age and Gender attribute. 
Created Seed file with faker gem

screen shot 2018-11-12 at 15 00 25

### CODE REVIEW

**Comment by tochman** [comment]
Please update PT link, if there's one and add screenshots.

**Comment by tochman** [comment]
@faraznaeem  This PR has merge conflicts that we can not fix on GH. The main problem is that we changed the way a user info is being displayed. We are using `remote: true` on the link AND displaying a pop-up/modal with the user info. That was introduced in one of the PR's merged yesterday.

**Review by tochman — COMMENTED** [review]
Is this one ready to go? There are no changes on the show page at the moment?

**Comment by faraznaeem** [comment]
Yes ready to go!

**Review by tochman — APPROVED** [review]
Looks good

**Pull request merged**
